### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by eexit** [moul/retry#5]
Hello,

Could you release `0.2.0` with newer features like the clear param?

Thanks,

**Comment by moul** [comment]
Sure, will do now :)

**Comment by moul** [comment]
- [x] Git tag: done
- [x] Homebrew manifest: done

**Comment by eexit** [comment]
@moul Awesome, just upgraded to the newest version :)

Thanks!

**Comment by moul** [comment]
:) if you have any ideas to make this tool more useful, please open new issues
